### ISSUE TITLE
Benny is hiding

### ISSUE THREAD

**Issue by jldugger** [osuosl/beaver-barcamp-pelican#11]
If you view the website on a non-mobile screen, benny is hidden behind a black bar.

Does this mean six more weeks of winter? :smirk:

**Comment by lucywyman** [comment]
@jldugger Is this still happening? I recently made some css changes, which likely did not fix the problem and in fact may have made it worse. Let me know!

**Comment by jldugger** [comment]
It looks "better" now that the bar is gone. The visual design seems to work best if his lower body is occluded by a bar, but I don't know how to fix it properly either =/
