### ISSUE TITLE
Change Site Name

### ISSUE THREAD

**Issue by kelnera** [osuosl/beaver-barcamp-pelican#21]
@osuosl/web-reviewers I've been looking for a way to change the site from Beaver Barcamp 16 to Beaver Barcamp 17 and I can't seem to find it. Does anyone know where that is?

**Comment by tschuy** [comment]
https://github.com/osuosl/beaver-barcamp-pelican/blob/master/pelicanconf.py#L6

**Comment by jldugger** [comment]
tschuy is correct, and you can use what you learned today about `git grep` to verify that!

```
$ git grep "Beaver Barcamp 16"
pelicanconf.py:SITENAME = u'Beaver Barcamp 16'
```

**Comment by kelnera** [comment]
Okay thanks! I was trying the git grep function and nothing was coming up.
