### ISSUE TITLE
Not sponsored by CoreOS (yet!?)

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/beaver-barcamp-pelican#23]
The site was updated but still says it's sponsored by CoreOS. If **I** were you I would replace the 'sponsored by' section with 'Sponsor this year's Beaver Barcamp', linking to a form to fill out for companies or individuals to request to sponsor the event.

Either way, you should at the very least remove the false info. It's misleading and might hinder the ability to get sponsors this year [citation needed].

CC: @osuosl/devs

**Comment by kelnera** [comment]
@ElijahCaine @ramereth It only says sponsored by CoreOS at the bottom of the screen. When you click on "Sponsor" in the menu bar, it says that if the visitor is interested in sponsoring Barcamp, to email beaverbarcamp.org. I can remove the CoreOS reference in the footer. Do we want to replace the email with a form? Do we also want to put it in the footer?

**Comment by ramereth** [comment]
Please keep the email and not setup a form. For the footer, maybe just remove the CoreOS and Sponsored by for now. We could maybe put something there about looking for sponsors as well.

**Comment by jldugger** [comment]
@kelnera I believe this issue has been resolved?

**Comment by kelnera** [comment]
@jldugger That is correct.
