### ISSUE TITLE
Tone it down with the font sizes

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/beaver-barcamp-pelican#6]
The `register` button shouldn't be below the fold. Let's tone down the font sizes to make it so the only thing below the fold is the footer.

**Comment by jldugger** [comment]
Who's fold? 

I nominally agree that the register button should be visible; even on my 1080p displays it's below the fold. But its worth thinking about how we approach 'the fold', as displays vary in size, and browser engines render differently. 

For example, are we going to go all the way down to mobile? Or 640x480? Is it worth our time to try something trickier, like responsive design techniques to algorithmically place the most important elements above the fold: https://css-tricks.com/responsive-web-above-the-fold/ ?

It may also be interesting to run an A/B experiment with a before & after design to estimate the size of the above-the-fold effect.

**Comment by jordane** [comment]
Closing as this has already been fixed well enough.
